### ISSUE TITLE
arrow keys not working [External module issue under Node 4.*/5.*]

### ISSUE THREAD

**Issue by totano** [OmniSharp/generator-aspnet#351] opened 2015-09-12 15:53 UTC
I followed the tutorial on VS Code website, installed latest aspnet-generator with npm install -g yo grunt-cli generator-aspnet bower and it went fine, but on the first choice of yo aspnet (application type) i cannot move the cursor with arrows. OS Windows 10

_Edit from Sayed_: For the latest status see https://github.com/nodejs/node/issues/2996

**Comment by peterblazejewicz** [comment] 2015-09-12 16:25
@totano 
Do you mean option select when generator starts? And that you cannot select one?

![image](https://cloud.githubusercontent.com/assets/14539/9832457/9a88b3fe-597b-11e5-8154-16699ca924f3.png)

**Comment by totano** [comment] 2015-09-12 16:50
yes

**Comment by peterblazejewicz** [comment] 2015-09-12 16:56
@totano Thanks!

The Yeoman uses Inquirer.js module for this: https://github.com/sboudrias/Inquirer.js
We need a help with testing the problem on Win10, any other folks can spot this problem?

**Comment by Spinarooni** [comment] 2015-09-13 12:39
It's working fine for me on my Windows 10 machine using yo 1.4.8 and node.js 0.12.6.

**Comment by peterblazejewicz** [comment] 2015-09-13 15:09
@Spinarooni 
Thanks! Appreciated

@sayedihashimi 
I assume you should have a Win10 machine in your team :)

@totano 
Can you let us know node version you're using? `node --version`, `yo --version`
This one `npm list -g --depth=0` should list version of generator installed on your machine
Thanks!

**Comment by totano** [comment] 2015-09-13 17:22
node v4.0.0
yo 1.4.8
npm
├── bower@1.5.2
├── generator-aspnet@0.0.73
├── grunt-cli@0.1.13
└── yo@1.4.8

**Comment by totano** [comment] 2015-09-13 17:24
there's an [issue](https://github.com/SBoudrias/Inquirer.js/issues/282) in inquirer, seems node 4 related

**Comment by peterblazejewicz** [comment] 2015-09-13 17:25
@totano 
Thanks! Something I though about :(

**Comment by Plinnio** [comment] 2015-09-14 10:30
I have exactly the same problem. I am on Windows 10, and the first time I created an application it worked, but now the arrow keys don't work when I have to select an application type.

**Comment by Spinarooni** [comment] 2015-09-14 14:38
@Plinnio Are you also running Node v4.0.0?

**Comment by Plinnio** [comment] 2015-09-14 15:22
@Spinarooni  Yes, this is the latest version I found.

**Comment by Spinarooni** [comment] 2015-09-14 15:28
@Plinnio If you want to roll back to 0.12 then you can download it from https://nodejs.org/dist/v0.12.7/.  The issue seems to be related to the Node 4.0.*.  It seems there is a bug in the Inquirer module: https://github.com/SBoudrias/Inquirer.js/issues/282

**Comment by Plinnio** [comment] 2015-09-14 15:44
@Spinarooni Thanks, how do I install that stuff?

**Comment by Spinarooni** [comment] 2015-09-14 17:02
@Plinnio If you 're on Windows 10 x64 then you could download the [MSI installer] (https://nodejs.org/dist/v0.12.7/x64/node-v0.12.7-x64.msi).  You may need to uninstall the current version first though.

**Comment by peterblazejewicz** [comment] 2015-09-14 18:44
ref: https://github.com/SBoudrias/Inquirer.js/issues/266

**Comment by Plinnio** [comment] 2015-09-15 09:25
After installing Node 0.12.6 the issue was solved. Thank you.

**Comment by peterblazejewicz** [comment] 2015-09-18 07:48
I had repeated the problem on Win 8.1 machine at work. Maybe I would be able to contribute somehow to external module
Node 4.1

**Comment by ditsikts** [comment] 2015-09-19 18:38
same thing here
node 4.1.0
yo 1.4.8

on the "yo -v" select list arrows works fine

**Comment by peterblazejewicz** [comment] 2015-09-19 18:47
@ditsikts Thanks very much. I've forwarded your tip about yo tool generator list selection to original module list

**Comment by peterblazejewicz** [comment] 2015-09-22 19:18
The problem is pinpointed and reposted to Node repo:
https://github.com/nodejs/node/issues/2996

**Comment by tienloc1** [comment] 2015-09-27 04:35
@Spinarooni thank so much your help, it is work good in cmd.exe, but it still not work in git bash.

**Comment by peterblazejewicz** [comment] 2015-09-27 07:35
Someone posted update about Node 4.1.1 fixing a problem:
https://github.com/SBoudrias/Inquirer.js/issues/282#issuecomment-143348244
I'll try tomorrow at work

**Comment by Spinarooni** [comment] 2015-09-27 13:47
@peterblazejewicz Tested on my Win 10 machine with Node 4.1.1 and I still have the issue at the command prompt and in PowerShell.  Works fine using Cmder.

**Comment by peterblazejewicz** [comment] 2015-09-27 13:51
@Spinarooni 
Thanks! I've PowerShell, CMD and GitBashon Win8.1 at work, so we will have a wide spectrum covered

**Comment by peterblazejewicz** [comment] 2015-09-28 13:30
Sadly, the 4.1.1 update does not resolve problem on my Win 8.1 at work (PowerShell, CMD, GitBash console environments).

**Comment by peterblazejewicz** [comment] 2015-09-29 09:33
I had no issues running a list of choices when using:
```
$ yo
? 'Allo Piotr! What would you like to do?
  ──────────────
  Run a generator
  Aspnet ♥ Update Available!
  Angular
> Karma
  ──────────────
  Update your generators
(Move up and down to reveal more choices)
```
cc:  @SBoudrias can give a hint?
https://github.com/yeoman/yo/blob/06f98c19ce58563c4a2f2653fcba9bca056f67a2/lib/routes/home.js#L63-L84
https://github.com/OmniSharp/generator-aspnet/blob/master/app/index.js#L27-L65
Maybe we should change implementation detail(s)?

**Comment by Spinarooni** [comment] 2015-09-29 11:11
@peterblazejewicz Can confirm.  I also noticed that if you run `yo` and then pick the aspnet generator you can move the selection arrow up and down to pick a project template.  When you run `yo aspnet` you can't move the selection arrow.  Weird.

**Comment by peterblazejewicz** [comment] 2015-09-29 18:30
@Spinarooni 
I'd research a topic if more people bump into that problem - this tool (generaor) seems to be crucial when supporting ASP.NET 5 in x-platform usage.
@sayedihashimi 
chance you folks in MS confirm (ACK) this issue internally?

**Comment by peterblazejewicz** [comment] 2015-09-30 06:51
Maybe the problem was nailed down in source:
https://github.com/nodejs/node/issues/2996#issuecomment-144200283

**Comment by scottaddie** [comment] 2015-10-09 18:24
I can also confirm that I'm seeing the arrow problem on Windows 10 Enterprise. It happens with both Cmder and cmd.exe. Here are my version numbers:

generator-aspnet 0.0.75
Node 4.1.2
NPM 3.3.6
yo 1.4.8

This seemed to break after upgrading from Node 0.12.7 to 4. On Windows 7 Enterprise, all is well; and, I'm using the same versions of everything listed above. I also found the latest comment from @Spinarooni to be true on Windows 10. That's the only way I can use this generator on Windows 10.

**Comment by peterblazejewicz** [comment] 2015-10-09 19:55
update on status: https://github.com/nodejs/node/issues/2996#issuecomment-146240124

**Comment by peterblazejewicz** [comment] 2015-10-12 06:40
https://github.com/Azure/azure-xplat-cli/issues/2175#issuecomment-147285945

**Comment by peterblazejewicz** [comment] 2015-10-20 13:43
I've no problem with Win 8.1 CMD console with recent Node 4.2.1. Only Bash based console seems to be affected still.

**Comment by joydesigner** [comment] 2015-11-02 02:10
I have the same issue with CMD, but the issue seems not exist when I using the powershell.

**Comment by cibien** [comment] 2015-11-03 01:14
I can reproduce the problem on a W10 Pro machine. It works using `yo -v` though.
Node: v4.1.2
yo: 1.5.0

**Comment by xabikos** [comment] 2015-11-08 21:08
A possible solution for the problem could be just to hit yo and then execute the required generator

**Comment by peterblazejewicz** [comment] 2015-11-09 19:43
That should be no problem soon as fixes are released in Node updates:
https://github.com/nodejs/node/issues/2996#event-458287743
We will update this issues resp.

**Comment by vandensd** [comment] 2015-11-12 17:07
Hello.  I'm also having the issue on Windows 10.  I don't think that it is only isolated to arrow keys but just keyboard capture in general.  For instance I could not terminate batch job also.

However, I did start from yo then choosing the generator and everything worked normal.

**Comment by prpatel2305** [comment] 2015-11-22 09:54
I am using windows 10 and node 5 v at first the arrow keys were not working with "yo aspnet" command 
then for just checking yo version I entered "yo -v" and it asked to select options my arrow keys start working :)

**Comment by SBoudrias** [comment] 2015-11-22 21:34
@prpatel2305 the bug is due to a race condition. If you start the generator from the `yo` menu, then it'll always work.

**Comment by kdcllc** [comment] 2015-12-04 18:14
@SBoudrias Thank you for the tip. I had the same issue and the propose fix it working great!

**Comment by peterblazejewicz** [comment] 2015-12-04 20:54
I think this is fixed on Win OS CMD and PowerShell with Node 5.1.*. I've tested Node 5.1.1 Stable build. The 4.2.3 LST build does not solve problem:
https://github.com/SBoudrias/Inquirer.js/issues/266#issuecomment-161967174
Someone can confirm?

**Comment by llamerr** [comment] 2015-12-07 10:10
@peterblazejewicz I just installed Node 5.1.1 (npm is 3.3.12) and it still doesn't work for me in Babun shell. But in Win OS CMD and PowerShell it works well, however it also works well in Node 4.2.3 (npm is 2.14.7) for those shells. 
Also when I'm using `yo generatorname` in babun (angular-fullstack in my case) and that menu appears, my cursor is disappearing afterwards (stop blinking).

**Comment by peterblazejewicz** [comment] 2015-12-21 19:22
update: it should be fixed with 4.2.4:
https://github.com/nodejs/node/issues/2996#issuecomment-166358700

**Comment by jimmy4701** [comment] 2015-12-22 12:12
I had the same problem with gitbash on windows 10.
My solution : use the cmd to launch the "yo" command. Arrow keys work fine in cmd.exe. Then when your app is installed, go back to your favorite terminal ;)

**Comment by peterblazejewicz** [comment] 2016-01-04 16:49
I've got a new machine at work with Win10. 
The 4.2.4 Node (current LTS version) works in all three terminals on this machine:
- Win CMD
- PowerShell
- Git Bash (Git for Windows)
If someone could confirm we can somehow instruct people on windows to update to this (or later) version of Node, maybe as post install hook.
Thanks!

**Comment by pumpi** [comment] 2016-01-20 13:15
after installing the new git bash not working on Win7 with it
I have install the latest stable version of node (v5.4.1)

**Comment by peterblazejewicz** [comment] 2016-01-20 20:38
@pumpi The LST 4.2.4 version has the same fix btw and it will be used as base release.

**Comment by jimmy4701** [comment] 2016-01-21 07:51
Another cool solution is to use 'cmder'. an emulation of consoles in nodejs to run multiple consoles in a same program on Windows. Cool design, a lot of commands (unix, windows... etc...)

**Comment by wolfhoundjesse** [comment] 2016-01-27 01:27
My keys work, but I found out on accident. The selector indicator never moves, but I can, in fact, choose items from the menu. You know, carefully.

Node 5.5
NPM 3.5.3
Windows 7
Git-Bash

**Comment by lincolnpires** [comment] 2016-01-27 16:53
I had the same problem.

But did as @Spinarooni said an voilá.
Ran `yo` and then picked the `aspnet generator`.

Win 8.1 Pro
npm 3.5.2
node 4.1.0

**Comment by ZhaoMiing** [comment] 2016-02-02 08:23
same issue here,
and solved after upgrade node to v5.5.0

**Comment by bastienJS** [comment] 2016-02-15 21:57
Does not work on:
Windows 10 64bit
Just did 
- npm install generator-aspnet
- yo aspnet
- arrows do nothing...
BUG

**Comment by peterblazejewicz** [comment] 2016-02-15 21:58
@bastienJS 
Please post Node/NPM version (I'm using Win10/64 at work).

**Comment by jeffpignataro** [comment] 2016-02-16 02:08
Also running Win10 x64. I'm having the same issue:
Node v5.6.0
NPM v3.7.2

Tried on numerous versions of Node and NPM 2.11.8 previously before upgrading.

**Comment by peterblazejewicz** [comment] 2016-02-29 16:48
This is a recurring problem. The NodeJS project is tracking issue here:
https://github.com/nodejs/node/issues/5384

**Comment by SalvatoreMeschini** [comment] 2016-04-10 14:58
Node version: 5.7.0
Npm version: 3.7.5
Yo: 1.7.0

Same issues here on Windows 10 64 bit :-(

**Comment by uurcakmak** [comment] 2016-04-13 09:02
Hi,

I'm having the same issue on Windows 10 64bit (Build 1511), with following versions,

node: 5.10.1
npm:  3.8.3
yo:     1.7.0

**Comment by pwombwa** [comment] 2016-04-16 17:07
@uurcakmak  @SalvatoreMeschini @peterblazejewicz @bastienJS @zhaomiing 
I had the same issue when I run **yo aspnet**
![error](https://cloud.githubusercontent.com/assets/7061532/14582445/e7a37fba-040d-11e6-9a52-d92d42cf994d.PNG)

The trick is to run **yo** then select **aspnet**  as the generator
![step1](https://cloud.githubusercontent.com/assets/7061532/14582471/7935ae8a-040e-11e6-804d-e8a6feb18d7f.PNG)

And now you should be able to use the arrow keys. 
![step2](https://cloud.githubusercontent.com/assets/7061532/14582475/8ec66596-040e-11e6-9c0c-ec03bcba20bd.PNG)

**Comment by peterblazejewicz** [comment] 2016-04-16 17:12
@pwombwa Thanks for the tips!

**Comment by jeffpignataro** [comment] 2016-04-16 18:17
After having reinstalled yo (amongst pretty much everything else including VS2015, npm, bower, git, npm, node, etc as part of VSCode/.NET Core reinstalls) it appears that yo aspnet is working fine for me now. I'm able to control it as expected. Unfortunately, I don't have a great answer as to what specifically what fixed it for me, but it does appear that reinstalls did fix the issue.

**Comment by SalvatoreMeschini** [comment] 2016-04-17 19:09
It's a bug: https://github.com/nodejs/node/issues/5384

**Comment by manfordbenjamin** [comment] 2016-05-08 23:03
Downgrade node and you'd be at peace :)

**Comment by projer** [comment] 2016-06-23 10:47
Made it work in Windows 10 (64 bits) with :
Node 4.1.1
Yeoman 1.8.3
Npm 3.8.6

But only in cmd.exe, doesn't work in Git Bash.

**Comment by Etrahkad** [comment] 2016-07-05 05:36
Windows Powershell fixes these issues.

**Comment by lizboccolini** [comment] 2017-04-26 04:02
I'm having the same issue with version 6.10.1 of node.

**Comment by peterblazejewicz** [comment] 2017-04-26 18:39
@lizboccolini 
What's your OS? While I cannot repeat that on OS X, these could be OS related problem in @SBoudrias/Inquirer.js (the lib behind dynamic list in yo)

**Comment by lizboccolini** [comment] 2017-04-26 18:46
Windows 10

**Comment by peterblazejewicz** [comment] 2017-04-26 18:48
@lizboccolini Thx, again, as work around try different shell terminal, for example I've been using PowerShell instead of Bash on Windows. Also: are you able to select any item just by typing 'yo' in terminal? (you should be offered a list of installed generators as default Yo action)

**Comment by lizboccolini** [comment] 2017-04-30 21:19
Using PowerShell solved it.  Thank you!

**Comment by peterblazejewicz** [comment] 2019-02-12 21:21
We are shutting this repo down, it's been replaced with `dotnet new`.

Thanks!

**Closed by peterblazejewicz** 2019-02-12 21:21 UTC
Labels: bug

**Comment by sayedihashimi** [comment] 2019-02-12 21:22
We are shutting this repo down, it's been replaced with `dotnet new`.
