### ISSUE TITLE
Location of the Dev environment relative links

### ISSUE THREAD

**Issue by rhires** [OmniSharp/generator-aspnet#339] opened 2015-09-09 02:09 UTC
When scaffolding the _Layout.cshtml page, the relative links for the Development environment point to ~/lib or ~/css, but with aspnet5, these items now live in wwwroot/lib and wwwroot/css and also at the same folder level as Shared, so the tilde is pointing at the wrong thing, too. In order for me to get it to work, I have to add this prefix in place of the tilde: 

```
../../../wwwroot/
```

To be able to access those items...

**Comment by Spinarooni** [comment] 2015-09-09 12:20
@rhires I'm not able to reproduce this with a new web application using the generator.  Is the `webroot` property in the project.json defined as `wwwroot`?
	
	{
		"webroot": "wwwroot"
	}

Maybe I'm missing something?

**Comment by peterblazejewicz** [comment] 2015-09-09 18:35
@rhires 
This is how in beta7 Razor/MVC resolves paths when using default tags:
https://github.com/aspnet/Announcements/issues/57
https://github.com/aspnet/Mvc/issues/3036
Does it help?

Please note that path resolution in Razor/MVC is probably better to be discussed on source project list:
https://github.com/aspnet/Mvc/issues

**Comment by rhires** [comment] 2015-09-09 22:34
@Spinarooni Project.json shows as you do...I contend that the generator is merely generating the incorrect paths in _Layout.cshtml, or that the template that the generator is using is wrong somehow. The reason I'm raising the issue here is that these are the defaults when I run the commands to start a default aspnet5 mvc project. On the other hand, perhaps it's Visual Studio Code that's misinterpreting these paths...

**Comment by rhires** [comment] 2015-09-10 01:13
On second thought, could this be a deeper issue since there is a spec that the generator is following?

**Comment by Spinarooni** [comment] 2015-09-10 18:40
@rhires The generator doesn't "generate" the paths in the file, those paths are static in the template file:

https://github.com/OmniSharp/generator-aspnet/blob/master/templates/projects/webbasic/Views/Shared/_Layout.cshtml#L8-L12

ASP.NET resolves the `~` in a path to refer to the web application's root folder when the page is rendered to the client.  So `~/lib/` should resolve to  `wwwroot/lib/` and `~/css/` should resolve to `wwwroot/css/` in the generator's default Web Application template.  Are you starting the application through VS Code or from the command line?

**Comment by rhires** [comment] 2015-09-20 01:11
Sorry, I didn't see your question at the end there. I am starting via the command line. When I comment out the "Staging,Production" environment, then the carousel (the easiest thing to test for) fails, presumably because the ~ cannot be resolved. 

Meanwhile, VSCode doesn't resolve the tilde at all. In fact, it creates a folder called "~" if I accept its prompt to create the path.

**Comment by peterblazejewicz** [comment] 2015-09-20 06:48
> When I comment out the "Staging,Production" environment, then the carousel (the easiest thing to test for) fails, presumably because the ~ cannot be resolved.

The templates are not yet shipping with full development tooling support unfortunately (they are created the same way as in Visual Studio)
From your console type:
```
npm init
bower init
gulp clean
gulp min
```
These will install NPM local modules, client side dependencies locally and prepare content.
Let me know if this works.

> VSCode doesn't resolve the tilde at all. In fact, it creates a folder called "~" if I accept its prompt to create the path.

The VSCode probably can't resolve Razor and/or ASP.NET 5 paths that use `Web Root` concept. It should take `project.json` configuration into account or use default `wwwroot` when resolving paths in Razor and use it as base path. It does not (at least I think it does not), so it fails. Please report it:
https://code.visualstudio.com/Issues/List

**Comment by rhires** [comment] 2015-09-20 12:46
Ok. [Reported](https://code.visualstudio.com/issues/detail/19429). 
Meanwhile, gulp isn't working for me for some reason, investigating that now. I'm getting an error about 'rimraf'...but this is turning out to be a rabbit hole I didn't intend to go down...

**Comment by peterblazejewicz** [comment] 2015-09-20 20:43
@rhires 
On fairly updated Node based development environment you should see following things executing mentioned elements from scaffolded projects:
```
npm install
npm WARN package.json Mvc.Client@0.0.0 No repository field.
npm WARN package.json Mvc.Client@0.0.0 No license field.
rimraf@2.2.8 node_modules/rimraf

gulp-uglify@1.2.0 node_modules/gulp-uglify
...
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, mkdirp@0.5.1, strip-bom@1.0.0, through2@0.6.5, defaults@1.0.2, vinyl@0.4.6, glob-stream@3.1.18, glob-watcher@0.0.6)
```
```
➜  bower install
bower jquery#2.1.4              cached git://github.com/jquery/jquery.git#2.1.4
bower jquery#2.1.4            validate 2.1.4 against git://github.com/jquery/jquery.git#2.1.4
....
bootstrap#3.0.0 wwwroot/lib/bootstrap
└── jquery#2.1.4
```
```
➜   ✗ gulp clean
[22:36:43] Warning: gulp version mismatch:
[22:36:43] Global gulp is 3.9.0
[22:36:43] Local gulp is 3.8.11
[22:36:44] Using gulpfile ~/git/asp5-mvc6-examples/Mvc.Client/gulpfile.js
[22:36:44] Starting 'clean:js'...
[22:36:44] Starting 'clean:css'...
[22:36:44] Finished 'clean:js' after 1.35 ms
[22:36:44] Finished 'clean:css' after 1.24 ms
[22:36:44] Starting 'clean'...
[22:36:44] Finished 'clean' after 4.29 μs
```
```
➜  Mvc.Client git:(master) ✗ gulp min
[22:36:49] Warning: gulp version mismatch:
[22:36:49] Global gulp is 3.9.0
[22:36:49] Local gulp is 3.8.11
[22:36:49] Using gulpfile ~/git/asp5-mvc6-examples/Mvc.Client/gulpfile.js
[22:36:49] Starting 'min:js'...
[22:36:49] Finished 'min:js' after 12 ms
[22:36:49] Starting 'min:css'...
[22:36:49] Finished 'min:css' after 3.94 ms
[22:36:49] Starting 'min'...
[22:36:49] Finished 'min' after 3.35 μs
```
Except of warnings (as I'm using most recent version of Gulp), there are just regular logs. 
If you get something different please start another ticket so we could help and investigate.

Let me know if we could close this ticket now.
Thanks!

**Comment by rhires** [comment] 2015-09-27 01:27
I figured it out: VSCode doesn't like the ~ in the editor itself (it's not converting it properly), but unless I have it in the path, dnx kestrel won't be able to resolve the local relative links properly. As for the gulp stuff, it's already there, since I use yoeman to scaffold the website...

**Comment by sayedihashimi** [comment] 2015-09-27 01:39
Adding @chrisdias

**Closed** 2018-04-11 10:39 UTC
