### ISSUE TITLE
Create new Web Application not change namespace name in _ViewImports.cshtml

### ISSUE THREAD

**Issue by mkielan** [OmniSharp/generator-aspnet#350] opened 2015-09-11 23:22 UTC
I create new web app project from template in aspnet generator (version 0.0.73)  with custom name.
Content of file Views/Shared/_ViewImports.cshtml: 
```
@using WebApplication
@using WebApplication.Models
@using WebApplication.ViewModels.Account
@using WebApplication.ViewModels.Manage
@using Microsoft.AspNet.Identity
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
```

So after command dnx kestrel and request to my application, a get exception:
```
error   : [Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware] An unhandled exception has occurred: One or more compilation failures occured:
Views/_ViewImports.cshtml(1,7): DNXCore,Version=v5.0 error CS0246: The type or namespace name 'WebApplication' could not be found (are you missing a using directive or an assembly reference?)
Views/_ViewImports.cshtml(2,7): DNXCore,Version=v5.0 error CS0246: The type or namespace name 'WebApplication' could not be found (are you missing a using directive or an assembly reference?)
```

Template should change namespace in this file.

**Comment by Spinarooni** [comment] 2015-09-12 00:24
@mkielan This was fixed: 

https://github.com/OmniSharp/generator-aspnet/commit/fe773043d1e49f1e9770af538e57275741d41e4a

@sayedihashimi Has this change not made it to NPM yet?

**Comment by sayedihashimi** [comment] 2015-09-12 01:16
It should have been released in 0.0.73. @mkielan what version do you have?

**Comment by mkielan** [comment] 2015-09-12 12:33
I wrote that my version is 0.0.73. Yesterday I installed the whole environment on my Mac OS X (generator by Yeoman). Today I try update it by NPM, but nothing has changed.

**Comment by peterblazejewicz** [comment] 2015-09-12 16:43
@sayedihashimi 
I can confirm this, maybe there is a problem in 0.0.73 release through NPM, my local installation has old code in template (non dynamic, static without namespace variable):
```
@using WebApplication
@using WebApplication.Models
@using WebApplication.ViewModels.Account
@using WebApplication.ViewModels.Manage
@using Microsoft.AspNet.Identity
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
```
We should make update to NPM I think

**Comment by peterblazejewicz** [comment] 2015-09-12 16:49
Clearing cache doesn't help either. That's really interesting as I had been already using 0.0.73 via NPM.
0.0.74? @sayedihashimi

**Comment by sayedihashimi** [comment] 2015-09-12 18:06
Ok thats really strange because I released that fix after @chrisdias reported it to me. He verified it was in 0.0.73. In either case we have some good updates so we can release 0.0.74.

@peterblazejewicz do u think we are ready to release now, or is there anything in progress that we should wait for?

**Comment by peterblazejewicz** [comment] 2015-09-12 18:07
I'm pushing two small PRs (one with gif update, second with that slashes) and we are ready to go. Couple of minutes at latest, OK?

**Comment by sayedihashimi** [comment] 2015-09-12 19:30
Ok sounds good, I will release later today

**Comment by peterblazejewicz** [comment] 2015-09-12 19:47
@sayedihashimi 
both are submitted - the  #354 should be tested on Windows if possible before merge
Thanks!

**Comment by johnciliberti** [comment] 2015-09-14 01:00
I can confirm that this bug still exists on Windows.

**Comment by peterblazejewicz** [comment] 2015-09-15 18:42
This is fixed in .74:
https://www.npmjs.com/package/generator-aspnet
I've tested manually to be sure the correct version is fetched from NPM:
```
@using <%= namespace %>
@using <%= namespace %>.Models
@using <%= namespace %>.ViewModels.Account
@using <%= namespace %>.ViewModels.Manage
@using Microsoft.AspNet.Identity
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
```

The *.74 version includes other small fixes and improvements btw.
Thanks!

**Comment by peterblazejewicz** [comment] 2015-09-15 18:44
https://twitter.com/sayedihashimi/status/643826331638063104

**Closed by peterblazejewicz** 2015-09-15 18:44 UTC
Labels: bug, completed
