### ISSUE TITLE
yo aspnet hangs when clicking on Key arrows

### ISSUE THREAD

**Issue by MaherJendoubi** [OmniSharp/generator-aspnet#448] opened 2015-10-31 14:20 UTC
![image](https://cloud.githubusercontent.com/assets/1798510/10864096/a5cc2a60-7fe2-11e5-94d4-104f6a48889d.png)

**Comment by MaherJendoubi** [comment] 2015-10-31 14:23
I am using nodejs v5.0.0 and npm v3.3.6!

**Comment by MaherJendoubi** [comment] 2015-10-31 14:24
![image](https://cloud.githubusercontent.com/assets/1798510/10864121/6cad7b7a-7fe3-11e5-9cf8-39ba1910a637.png)

**Comment by sayedihashimi** [comment] 2015-10-31 15:20
Sounds like https://github.com/OmniSharp/generator-aspnet/issues/351

**Comment by MaherJendoubi** [comment] 2015-10-31 15:35
@sayedihashimi  Sorry I didn't see it.

![image](https://cloud.githubusercontent.com/assets/1798510/10864408/6f8a3054-7fed-11e5-9414-df60c9a14fce.png)

**Comment by sayedihashimi** [comment] 2015-10-31 16:47
Ok so I'll close this now, if the issue is different from the linked one please reopen with details.

**Closed by sayedihashimi** 2015-10-31 16:47 UTC

**Comment by MaherJendoubi** [comment] 2015-11-01 00:28
@sayedihashimi it's a different problem because key arrows hang when I run yo aspnet but when I do yo then I chose aspnet key arrows work.

**Comment by MaherJendoubi** [comment] 2015-11-01 00:33
Hey @sayedihashimi,   here are the details:
It works like this when I type yo
![image](https://cloud.githubusercontent.com/assets/1798510/10866628/2be0bd00-8038-11e5-84ee-c4de627d1b8d.png)

But it hangs when I write diretly yo aspnet
![image](https://cloud.githubusercontent.com/assets/1798510/10866630/62dba6da-8038-11e5-838d-8c906f66a9e5.png)

Hope this help you.
Thanks.

Maher

**Comment by peterblazejewicz** [comment] 2015-11-01 15:47
> it's a different problem because key arrows hang when I run yo aspnet but when I do yo then I chose aspnet key arrows work.

Not exactly, that's the same behavior:
https://github.com/OmniSharp/generator-aspnet/issues/351#issuecomment-144006034

The Node team works on fixing this problem

**Comment by MaherJendoubi** [comment] 2015-11-02 00:38
@peterblazejewicz thank you for the feedback!
