### ISSUE TITLE
Change log / Version history?

### ISSUE THREAD

**Issue by Brad-Christie** [OmniSharp/generator-aspnet#564] opened 2016-02-16 22:54 UTC
Is it possible to get a change log/version history? I realize, given sem-ver guidelines, 0.0.92->0.0.93 is not a significant change, but it would be helpful to know what was changed. Plus, it would make for a good habit moving forward. All I have to go by currently is to checkout the release branch and cruise commits.

Even if you added it to the [version uptick](https://github.com/OmniSharp/generator-aspnet/commit/3569caf42f8ed4e276d28a8b89476ce1e24efb07) commit it would be helpful.

Just a thought.

p.s. I'm sorry this project has lost traction; I loved seeing this when dnx was just getting going, but saw the team let is drop to the wayside and focus on VS tooling. Just my $0.02: this is crucial for gaining traction in an OS agnostic environment, and this module is still heavily referenced on StackOverflow and other mediums. Any/all work done on this repo is _very_ much appreciated. My hat's off to the contributors.

**Comment by spboyer** [comment] 2016-02-16 23:03
@Brad-Christie this project hasn't lost traction at all. It is still very relevant and a part of every release cycle.  

Will certainly take the suggestion on the release notes. Compiling the PRs from release to release is the task.

**Comment by sayedihashimi** [comment] 2016-02-17 01:47
@Brad-Christie yeah we just pushed a release last week. I agree release notes would be nice. Maybe there is a standard way/script that other generators use?

**Comment by sayedihashimi** [comment] 2016-02-17 01:58
Btw I've purposefully taken a step back and let @peterblazejewicz, @spboyer and the other community members take a bigger role in this project. That's not due to my lack of interest, it's by design and has a lot of benefits.

 - It gives community members a chance to make meaningful contributions to an important project
 - The community members keep us (Microsoft team) in check when we try to add things that don't make sense or introduce bugs
 - It gives more credibility since the community is a core part of this project
 - It helps me internally promote engaging with the community by being an example of where great things happen when we work together. 

Since @peterblazejewicz and @spboyer are doing such a great job you're not seeing much of me here, but that doesn't mean that I'm not here.

I am still very interested and committed to this project. And it will be a part of my formal yearly review at Microsoft.

**Comment by Brad-Christie** [comment] 2016-02-17 14:05
@spboyer My apologies, wasn't insinuating it was going nowhere, I was just referencing a previous  [announcement](https://github.com/aspnet/Announcements/issues/102) by @sayedihashimi. I'm glad to hear it's still being actively worked on (just haven't seen much activity as of late I guess--or have missed it).

**Comment by sayedihashimi** [comment] 2016-02-17 16:05
Right now scaffolding and new project/item are in different projects. Once make good progress on cmd line scaffolding we will have to figure out how to combine the experience later. Activity has slowed down a bit here because the asp.net release itself was delayed.

**Comment by sayedihashimi** [comment] 2016-02-17 16:08
Fyi I added a line to that announcement clarifying it has no impact on this project.

**Comment by peterblazejewicz** [comment] 2016-02-17 17:49
@Brad-Christie 
Thanks for feedback! Yes, there is a `post-rc1-era-before-dotnet-cli`, but I'm afraid you are exaggerating a little bit! :)
> Is it possible to get a change log/version history?

There is no GitHub supported release feature used to track releases, just tagging for NPM version release. It would be useful, but project started without it and it just works without this.

> I'm glad to hear it's still being actively worked on (just haven't seen much activity as of late I guess--or have missed it).

We are all aware I hope that folks at MS keep rewriting .Net Core after RC1 (and RC1-final-update1), so people just use this tool:
![image](https://cloud.githubusercontent.com/assets/14539/13118829/5f13b38a-d5a6-11e5-953c-da00f77e847a.png)
The project does not change frequently, as it is used in docs, so its features/ux can't just change overnight. The project started with 10k/month this year, now it has 13k/month.
Thanks!

**Comment by peterblazejewicz** [comment] 2016-02-17 17:52
@sayedihashimi 
After RTM and where is still a need for this tool, let's use GitHub releases. That will help people. I'm used to `Release` feature on GitHub too, so @Brad-Christie has my support in this.

**Comment by sayedihashimi** [comment] 2019-02-12 21:19
We are shutting this repo down, it's been replaced with `dotnet new`.

**Closed by sayedihashimi** 2019-02-12 21:19 UTC
