### ISSUE TITLE
Nancy template doesn't run on beta7

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/generator-aspnet#328] opened 2015-09-02 18:01 UTC
When running the Nancy template with beta7 we get the following error.

```
System.InvalidOperationException: No service for type 'Microsoft.Framework.Runtime.IApplicationEnvironment' has been registered.
  at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService (IServiceProvider provider, System.Type serviceType) <0x109547340 + 0x00073> in <filename unknown>:0
  at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T] (IServiceProvider provider) <0x1095472c0 + 0x00032> in <filename unknown>:0
  at Microsoft.AspNet.Hosting.Program.Main (System.String[] args) <0x109545e10 + 0x000f8> in <filename unknown>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x106e1afd0 + 0x000a3> in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x106c70510 + 0x00029> in <filename unknown>:0
  at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute (System.Reflection.Assembly assembly, System.String[] args, IServiceProvider serviceProvider) <0x109544b40 + 0x001cd> in <filename unknown>:0
  at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain (Microsoft.Dnx.Runtime.DefaultHost host, System.String applicationName, System.String[] args) <0x107df71f0 + 0x0039b> in <filename unknown>:0
  at Microsoft.Dnx.ApplicationHost.Program.Main (System.String[] args) <0x107da8380 + 0x00637> in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () in <filename unknown>:line 0
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute (System.Reflection.Assembly assembly, System.String[] args, IServiceProvider serviceProvider) in <filename unknown>:line 0
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync (System.Collections.Generic.List`1 args, IRuntimeEnvironment env, System.Runtime.Versioning.FrameworkName targetFramework) in <filename unknown>:line 0
Sayeds-MacBook-Pro:NancyApplication sayedhashimi$ dnx kestrel
```

cc @jchannon

**Comment by jchannon** [comment] 2015-09-02 18:08
Bug in DNX? Looks like it's trying to find a interface registration in the
aspnet DI which Nancy probably won't use

**Comment by PinpointTownes** [comment] 2015-09-02 18:11
@jchannon are you sure it's not simply caused by a packages/DNX runtime versions mismatch?

**Comment by sayedihashimi** [comment] 2015-09-02 18:13
@jchannon @PinpointTownes I'm not sure I haven't investigate it yet. I was hoping that either @jchannon or someone else would be able to. I think it's probably some refactoring that has happened and we need to add a new dependency to it.

**Comment by peterblazejewicz** [comment] 2015-09-02 18:39
@sayedihashimi 
I'm getting the same:
```
dnx kestrel
System.InvalidOperationException: No service for type 'Microsoft.Framework.Runtime.IApplicationEnvironment' has been registered.
```

**Comment by jchannon** [comment] 2015-09-02 18:45
OK this works for beta7 on my machine

Its posiblly because the nancy project.json has 1.0.0-* and I suspect is
pulling in beta8 packages??

**Comment by peterblazejewicz** [comment] 2015-09-02 18:49
with this bits:
```
"dependencies": {
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-beta7",
        "Microsoft.AspNet.Owin": "1.0.0-beta7",
        "Nancy": "1.2.0"
    },
```
it does work on my OS X machine, should I make PR?
@sayedihashimi can you quickly test?

**Comment by sayedihashimi** [comment] 2015-09-02 18:51
I'm busy for the next hour bit will try it soon after that.

**Comment by jchannon** [comment] 2015-09-02 18:52
actually it works fine "as is" so maybe @sayedihashimi has a dodgy setup?

**Comment by peterblazejewicz** [comment] 2015-09-02 18:52
@jchannon 
I had to make above changes in `project.json` to make current template work with setup for beta7 we used for other templates

**Comment by jchannon** [comment] 2015-09-02 18:53
<img width="855" alt="screen shot 2015-09-02 at 19 53 19" src="https://cloud.githubusercontent.com/assets/105126/9641004/4b22ab98-51ac-11e5-8f15-e85caf287854.png">

Works on my machine! :smile:

**Comment by jchannon** [comment] 2015-09-02 19:37
Merged PR with beta7 explicitly defined

**Closed** 2015-09-02 19:37 UTC
Labels: beta7, bug, help wanted

**Comment by peterblazejewicz** [comment] 2015-09-02 19:43
also:
https://github.com/OmniSharp/generator-aspnet/pull/331
